% plot_validation.m
%
% Generate a scatter plot and PfPR versus either a cases per 1000 plot, or
% and incidence plot using the validation data provied. Note that the 
% function assumes that the data was generated by the getverificationstudy 
% script.
%
% Optional paramters:
% age - 59 (0 - 59 months) or 120 (2 - 10 years)

function [] = plot_validation(modelData, unreported, varargin)
    REFERENCE = 'data/uga-weighted_pfpr_district.csv';

    subplot(1, 2, 1);
    y_maxima = plot_comparison(modelData, REFERENCE, varargin{:});

    % Plot the case data
    subplot(1, 2, 2);
    plot_cases_pfpr(modelData, unreported, y_maxima, varargin{:});   
    
    % Append the country name if supplied
    inputExist = find(cellfun(@(x) strcmpi(x, 'country') , varargin));
    if inputExist
        sgtitle(sprintf('%s Validation Metrics', varargin{inputExist + 1}), 'FontSize', 24);
    end
end

function [y_maxima] = plot_comparison(modelData, referenceData, varargin)
    CENTER_MIN = 0;

    % Data seperator
    fprintf("--- District Prevalence ---\n");

    % Parse the arguments
    [pfprIndex, ageBand] = parseAge(varargin{:});

    % Load the data
    reference = readmatrix(referenceData);
    [data, districts] = load(modelData, 11 * 365, 16 * 365);

    % Since the MAP values are the mean, we want to compare against the
    % mean of our data, but highlight the seasonal minima and maxima
    x_maxima = 0; y_maxima = 0;
    hold on;
    for district = transpose(districts)
        expected = reference(reference(:, 1) == district, 2);
        pfpr = data(data(:, 2) == district, pfprIndex); 
        
        % We want the seasonal maxima, filter out the local maxima, once
        % this is done we should only have six points left
        maxima = pfpr(pfpr > mean(pfpr));
        maxima = maxima(maxima > maxima - std(maxima));
        maxima = findpeaks(maxima);
        
        % Repeat the same process for the minima as the maxima
        minima = pfpr(pfpr < mean(pfpr)) .* -1;
        minima = minima(minima > minima - std(minima));
        minima = findpeaks(minima);

        % Plot from the maxima to the minima, connected by a line
        line([expected expected], [mean(maxima) abs(mean(minima))], 'LineStyle', '--', 'LineWidth', 1.5, 'Color', 'black');
        scatter(expected, mean(maxima), 75, [99 99 99] / 255, 'filled', 'MarkerEdgeColor', 'black');
        scatter(expected, mean(pfpr), 150, [99 99 99] / 127.5, 'filled', 'MarkerEdgeColor', 'black');
        scatter(expected, abs(mean(minima)), 75, [99 99 99] / 255, 'filled', 'MarkerEdgeColor', 'black');

        % Note the maximum so we can format the plot correctly
        if max(maxima) > y_maxima
            y_maxima = ceil(max(maxima) / 2.5) * 2.5;
        end      
        if max(mean(pfpr)) > x_maxima
            x_maxima = ceil(max(mean(pfpr)) / 5) * 5.5;
        end

        % Report the distirct metrics
        fprintf('%d: Expected: %.2f; Simulation: %.2f\n', district, expected, mean(pfpr));
    end
    hold off;
    
    % Set the limits
    xlim([CENTER_MIN x_maxima]);
    ylim([CENTER_MIN y_maxima]);
    
    % Plot the reference error lines
    data = get(gca, 'YLim');
    for value = [0.9 0.95 1.05 1.1]
        line([data(1) data(2)], [data(1)*value data(2)*value], 'Color', [0.5 0.5 0.5], 'LineStyle', '-.');
    end
    line([data(1) data(2)], [data(1) data(2)], 'Color', 'black');
    
    text(x_maxima, x_maxima + 0.5, '\pm0%', 'FontSize', 16);
    text(x_maxima, x_maxima * 0.95, '-5%', 'FontSize', 16);
	text(x_maxima, x_maxima * 0.9, '-10%', 'FontSize', 16);
    
    % Label and format the plot
    ylabel(sprintf('Simulated {\\itPf}PR_{%s}', ageBand));
    xlabel(sprintf('Reference {\\itPf}PR_{%s}', ageBand));
    format();
end

function [] = plot_cases_pfpr(modelData, unreported, y_maxima, varargin)
    CSV_POPULATION = 3; CSV_CASES = 4; CSV_REPORTED = 5; 
    
    % Data seperator
    fprintf("\n--- District Cases ---\n");

    % Set the treatment rate if supplied
    treatment_rate = 1.0;
    inputExist = find(cellfun(@(x) strcmpi(x, 'treated'), varargin));
    if inputExist
        treatment_rate = varargin{inputExist + 1};
    end
    [pfprIndex, ageBand] = parseAge(varargin{:});

    % Load the data
    [data, districts] = load(modelData, 12 * 365, 13 * 365);
    
    % Prepare the arrays
    cases = zeros(size(districts, 1), 1);
    treated = zeros(size(districts, 1), 1);
    reported = zeros(size(districts, 1), 1);
    pfpr = zeros(size(districts, 1), 1);
    
    % Add the points
    ndx = 1;
    population = 0;
    for district = transpose(districts)
        filtered = data(data(:, 2) == district, :);
        cases(ndx) = sum(filtered(:, CSV_CASES)) / (max(filtered(:, CSV_POPULATION)) / 1000);
        treated(ndx) = (sum(filtered(:, CSV_REPORTED)) * treatment_rate) / (max(filtered(:, CSV_POPULATION)) / 1000);
        reported(ndx) = treated(ndx) * (1 - unreported);

        pfpr(ndx) = mean(filtered(:, pfprIndex));

        fprintf('%d: Cases: %.2f; Treated: %.2f; Reported: %.2f\n', ndx, cases(ndx), treated(ndx), reported(ndx))
        population = population + max(filtered(:, CSV_POPULATION));

        ndx = ndx + 1;
    end

    % Switch the plotting data to log10
    cases = log10(cases);
    treated = log10(treated);
    reported = log10(reported);

    % NOTE These are absolute values from the simuation data, if population
    % scaling is applied they may need to be adjusted to approximate real
    % projections
    fprintf('Total Simulation Clinical Cases: %.2f\n', sum(data(:, CSV_CASES)));
    fprintf('Total Simulation Cases Treated: %.2f\n', sum(data(:, CSV_REPORTED)));
    fprintf('Total Simulation Cases Reported: %.2f\n', (sum(data(:, CSV_REPORTED))) * (1 - unreported));

    fprintf('Total Incidence: %.2f / 1000\n', sum(data(:, CSV_CASES)) / (population / 1000));
    fprintf('Total Cases: %.2f - %.2f / 1000\n', ...
        sum(data(:, CSV_REPORTED) * (1 - unreported)) / (population / 1000), ...
        sum(data(:, CSV_REPORTED)) / (population / 1000));

    hold on;
    scatter(cases, pfpr, 125, [0.6350 0.0780 0.1840], 'filled', 'MarkerEdgeColor', 'black', 'MarkerFaceAlpha', 0.75);
    scatter(treated, pfpr, 125, [0.9290 0.6940 0.1250], 'filled', 'MarkerEdgeColor', 'black', 'MarkerFaceAlpha', 0.5);    
    scatter(reported, pfpr, 125, [0.4660 0.6740 0.1880], 'filled', 'MarkerEdgeColor', 'black', 'MarkerFaceAlpha', 0.5);    
    
    % Fix the legend
	legend({'Total Cases', 'Treated Cases', 'Reported Cases'}, 'Location', 'NorthWest', 'AutoUpdate', 'off');

    % Add the incidence rate and CrI if supplied
    inputExist = find(cellfun(@(x) strcmpi(x, 'ci'), varargin));
    if inputExist
        ci = varargin{inputExist + 1};
        xline(log10(ci(1)), '-', 'Estimated Incidence Rate', 'LineWidth', 1.5, 'FontSize', 16);
        xline(log10(ci(2)), '-.', '95% Credible Interval', 'FontSize', 16);
        patch(log10([ci(2) ci(3) ci(3) ci(2)]), [0 0 100 100], [99 99 99] / 104);
        set(gca, 'children', flipud(get(gca,'children')));
    end
    hold off;
    
    % Determine the bounds
    x_maxima = max(cases);
    x_maxima = floor(x_maxima) + ceil((x_maxima - floor(x_maxima)) / 0.25) * 0.25;
    x_minima = min(reported);
    x_minima = floor(x_minima) + floor((x_minima - floor(x_minima)) / 0.25) * 0.25;

    % Format the log10 axis
    ylim([0 y_maxima]);
    xlim([x_minima x_maxima]);
    xticks(log10([0 10 25 50 100 200 400 600 1000 1500 2000]));
    xticklabels(split(num2str([0 10 25 50 100 200 400 600 1000 1500 2000])));
    
    % Label and format the plot
    xlabel('Clinical Cases per 1,000');
    ylabel(sprintf('Simulated {\\itPf}PR_{%s}', ageBand));
    legend boxoff;
    format();
end

function [] = format()
    pbaspect([1 1 1]);
    graphic = gca;
    graphic.FontSize = 18;
end

function [data, districts] = load(filename, startDate, endDate)
    data = readmatrix(filename);
    data = data(data(:, 1) >= startDate, :);
    data = data(data(:, 1) <= endDate, :);
    districts = unique(data(:, 2));
end

% Set the age banding if it is provided, default is 2 to 10
function [pfprIndex, ageBand] = parseAge(varargin)
    CSV_PFPR0TO59 = 7; CSV_PFPR2TO10 = 8;

    pfprIndex = CSV_PFPR2TO10;
    ageBand = '2 to 10';
    inputExist = find(cellfun(@(x) strcmpi(x, 'age'), varargin));
    if inputExist
        if varargin{inputExist + 1} == 59
            pfprIndex = CSV_PFPR0TO59;
            ageBand = '0 to 59';
        elseif varargin{inputExist + 1} ~= 120
            error('Unknown value for age: %d, expected 59 or 120', varargin{inputExist + 1});
        end
    end    
end